type
    ResultError* = object of Exception
